# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
"rocks-config.nvim" = "3.0.0"
neorg = "9.1.1"
"rocks-git.nvim" = "2.3.1"
nvim-treesitter= "0.9.2"
"rocks-treesitter.nvim" = "scm"
tree-sitter-norg-meta = "0.1.0"
"rocks-dev.nvim" = "1.7.0"
nvim-cmp = "scm"

[plugins."plenary.nvim"]
git = "nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins."nui.nvim" ]
git = "muniftanjim/nui.nvim"
rev = "0.3.0"

[plugins."packer.nvim"]
git = "wbthomason/packer.nvim"
rev = "ea0cc3c59f67c440c5ff0bbe4fb9420f4350b9a3"

[plugins."iceberg.vim"]
git = "cocopon/iceberg.vim"
rev = "1.0^{}"

[plugins.vim-rooter]
git = "airblade/vim-rooter"
rev = "4a0df2f1b0f3d69e8f7e19afe464a7c3a7af89a2"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7^{}"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.7.0^{}"

[plugins.vim-surround]
git = "tpope/vim-surround"
rev = "v2.2^{}"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "nvim-0.6"

[plugins."project.nvim"]
git = "ahmedkhalf/project.nvim"
rev = "8c6bad7d22eef1b71144b401c9f74ed01526a4fb"

[plugins."symbols-outline.nvim"]
git = "simrat39/symbols-outline.nvim"
rev = "564ee65dfc9024bdde73a6621820866987cbb256"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.9.0"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"
rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa"

[plugins.nvim-dap]
git = "mfussenegger/nvim-dap"
rev = "0.8.0^{}"

[plugins.nvim-dap-python]
git = "mfussenegger/nvim-dap-python"
rev = "d777c2b32ed39f61209c09bede28d7491621a631"

[plugins.rainbow_csv]
git = "mechatroner/rainbow_csv"
rev = "4.3.0"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"
rev = "a6d0127a53d39b9fc2af75bd169d288166118aec"

[plugins."gen.nvim"]
git = "David-Kunz/gen.nvim"
rev = "b1230ce2993b2be38a1e22606750d05a94307380"

[plugins."Comment.nvim"]
git = "numToStr/Comment.nvim"
rev = "v0.8.0"

[plugins."null-ls.nvim"]
git = "jose-elias-alvarez/null-ls.nvim"
rev = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7"

[plugins."mason-null-ls.nvim"]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins.nvim-dap-ui]
git = "rcarriga/nvim-dap-ui"
rev = "v4.0.0"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"
rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v1.0.0"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"
rev = "v1.2.3"

[plugins."gundo.vim"]
git = "sjl/gundo.vim"
rev = "v2.6.2"

[plugins."kanagawa.nvim"]
git = "rebelot/kanagawa.nvim"
rev = "e5f7b8a804360f0a48e40d0083a97193ee4fcc87"

[plugins."flutter-tools.nvim"]
git = "akinsho/flutter-tools.nvim"
rev = "v1.9.1"

[plugins."geno.nvim"]
dir = "~/workspace/neovim/geno.nvim/"

[plugins.vim-table-mode]
git = "dhruvasagar/vim-table-mode"
rev = "v4.8.1^{}"

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"
rev = "c6bfb191f1161fbabace1f36f578a20ac6c7642c"

[plugins."trouble.nvim"]
git = "folke/trouble.nvim"
rev = "v3.6.0"

[plugins."todo-comments.nvim"]
git = "folke/todo-comments.nvim"
rev = "v1.4.0"

[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
rev = "compat-nvim-0.6"
