# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.19.0" # rocks.nvim can also manage itself :D
"rocks-config.nvim" = "1.6.0"
neorg = "8.6.0"
"rocks-git.nvim" = "1.5.1"
nvim-treesitter= "0.9.2"
"rocks-treesitter.nvim" = "scm"

[plugins."plenary.nvim"]
git = "nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins."packer.nvim"]
git = "wbthomason/packer.nvim"

[plugins."iceberg.vim"]
git = "cocopon/iceberg.vim"
rev = "1.0^{}"

[plugins.vim-rooter]
git = "airblade/vim-rooter"

[plugins.vim-airline]
git = "vim-airline/vim-airline"
rev = "v0.9"

[plugins.vim-airline-themes]
git = "vim-airline/vim-airline-themes"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7^{}"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.8.1"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.3.3"

[plugins.vim-surround]
git = "tpope/vim-surround"
rev = "v2.2^{}"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "nvim-0.6"

[plugins."project.nvim"]
git = "ahmedkhalf/project.nvim"

[plugins."symbols-outline.nvim"]
git = "simrat39/symbols-outline.nvim"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.9.0"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "v0.0.1"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.nvim-dap]
git = "mfussenegger/nvim-dap"
rev = "0.8.0^{}"

[plugins.nvim-dap-python]
git = "mfussenegger/nvim-dap-python"

[plugins.rainbow_csv]
git = "mechatroner/rainbow_csv"
rev = "4.3.0"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"

[plugins."gen.nvim"]
git = "David-Kunz/gen.nvim"

[plugins."Comment.nvim"]
git = "numToStr/Comment.nvim"
rev = "v0.8.0"

[plugins."null-ls.nvim"]
git = "jose-elias-alvarez/null-ls.nvim"

[plugins."mason-null-ls.nvim"]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins.nvim-dap-ui]
git = "rcarriga/nvim-dap-ui"
rev = "v4.0.0"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v0.1.8"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"
rev = "v1.2.0"

[plugins."gundo.vim"]
git = "sjl/gundo.vim"
rev = "v2.6.2"

[plugins.undotree]
git = "mbbill/undotree"
rev = "rel_6.1"

[plugins."copilot.vim"]
git = "github/copilot.vim"
rev = "v1.9.4"

[plugins."kanagawa.nvim"]
git = "rebelot/kanagawa.nvim"

[plugins."flutter-tools.nvim"]
git = "akinsho/flutter-tools.nvim"
rev = "v1.9.1"
